<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title> Google Drive App </title>
        <link href="./style.css" rel="stylesheet" type="text/css">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    </head>
    <body>
    <nav class='navbar navbar-dark site-header sticky-top py-1'>  
        <i class='fas fa-arrow-left fa-2x' id='back-page'></i>
    </nav>
    <div class="jumbotron">
        <h1 class="display-4">Drive Upload</h1>
            <p class="lead">We will upload your folder to your drive, please click on Upload button to upload... 😃 </p>
            <hr class="my-4">
            <p class="lead">
                <form method="post" action="<?php echo $url; ?>">
                    <input class="btn btn-primary" type="submit" value="Upload" name="submit">
                </form>
            </p>
    </body>
<script>
    document.getElementById('back-page').addEventListener('click', function(){
        window.history.go(-1);
    });
</script>
</html>
